/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
#include "/usr/lib/jvm/java-7-openjdk-amd64/include/jni.h"

/* Header for class hr_foi_tiwo_ObjDec */

#ifndef _Included_hr_foi_tiwo_ObjDec
#define _Included_hr_foi_tiwo_ObjDec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hr_foi_tiwo_ObjDec
 * Method:    sendImageForProcessing
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_hr_foi_tiwo_ObjDec_sendImageForProcessing
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
